### ISSUE TITLE
Rotator Sync Offset Restore

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/Conform#10]
The Position and SyncOffset of a rotator are persisted in the ASCOM Profile store. 
It could be more useful if Conform restored the original values of those properties after a Conform run is finished.

**Comment by Peter-Simpson** [comment]
Hi Rick,

I've made Conform do this as far as I can. Conform can't determine the sync offset for IRotatorV1/2 devices because they don't have the MechanicalPosition property. For these interfaces, Conform just restores the rotator position. For IRotatorV3 devices, Conform restores both the position and sync offset.

BTW, I found a bug in the Platform simulator if the Move method is used immediately after starting the simulator without any preceding MoveAbsolute call, (which is the case in this fix). Consequently so you may find odd results when testing this fix.

Best wishes, Peter
