### ISSUE TITLE
Some additional checks conform could perform

### ISSUE THREAD

**Issue by 3ricj** [ASCOMInitiative/Conform#6]
I've been finding bugs with mounts and drivers -- most often conform finds these bugs but I've found a few cases where it misses them.  I just wanted to write up a few ideas and send them your way.  Thanks for making conform, it's great.  Onto the ideas: 

1.  Check if the tool/driver is running as admin - I've had a driver flat out refuse to run if it's not running as admin (avalon) which is in violation of ascom standards, if I understand them correctly. 

2.  Long-term stability -- I've had drivers fail after running for some duration (I perform lots of move/shoot/move commands) and so I'd love a mode in conform where I could leave it to run/test repeatedly or until we stop it.  

3.  Different output based on time - related to the above idea, I had a "side of pier" error only crop up sometimes (maybe a bad switch in my mount?) that was extremely hard to nail down -- this was causing my guider to sometimes freak out and push the scope in the wrong direction.  I was getting different results with each run of conform -- due to this interment switch problem.  It could be possible for conform to check each run for the same output.  

Thanks again!

**Comment by Peter-Simpson** [comment]
Hi,

Thanks very much for your ideas. I can't see a way of addressing 1. because Conform doesn't know what process the driver is running in. Applications like Conform access drivers through COM, which hides out of process COM servers from COM clients and doesn't provide information such as ProcessID that is required to implement this functionality.

I've also assessed the work required to deliver 2. and 3 and it is really substantial because Conform does not store test outcomes, simply reporting them as it runs through the tests. A whole new storage mechanic would be required to support time based testing together with a lot of UI work to provide control handles and reporting for the tests; there are also 10 device types that the tests would have to cover.

I think that this amount of effort can deliver more benefit in other areas so regrettably I am not going to implement your helpful suggestions.

Best wishes, Peter
