### ISSUE TITLE
Conform returns error with Covercalibrator if response is moving after opencover

### ISSUE THREAD

**Issue by skybadger** [ASCOMInitiative/Conform#7]
Using conform 6.5.7500.22515 against alpaca covercalibrator remote device 

From the conform output: 
Methods 
15:57:55.502 OpenCover                                  About to call OpenCover method
15:57:56.065 OpenCover                         ERROR    OpenCover was unsuccessful - the returned CoverState was 'Moving' instead of 'Open'. The synchronous open took 0.6 seconds

I believe this is an error since the api states that the api call intiates the coveropening and should not expect to see only coveropen as a response. 
thoughts ?

**Comment by Peter-Simpson** [comment]
This turned out to be a device issue as documented [here](https://ascomtalk.groups.io/g/Developer/topic/87838750).  Conform will be updated to include more comprehensive messaging indicating that the error can also arise when the status property is not set before the Alpaca device returns control the originator.
